resource_types:
- name: semver-iam
  type: docker-image
  source:
    repository: governmentpaas/semver-resource
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:
- name: check-buildpack-updates
  type: time
  source: {interval: 60m}
- name: notify-src
  type: git
  source:
    uri: ((cg-buildpack-notify))
    branch: ((cg-buildpack-notify-branch))
- name: cg-buildpack-notify-deploy-staging
  type: cf
  source:
    api: ((cf-api-staging))
    username: ((deployer-username-staging))
    password: ((deployer-password-staging))
    organization: ((cf-org-staging))
    space: ((cf-space-staging))
- name: cg-buildpack-notify-deploy-production
  type: cf
  source:
    api: ((cf-api-production))
    username: ((deployer-username-production))
    password: ((deployer-password-production))
    organization: ((cf-org-production))
    space: ((cf-space-production))
- name: pull-request
  type: pull-request
  source:
    repo: ((cg-buildpack-notify-github-repo-name))
    access_token: ((status-access-token))
    every: true
- name: slack
  type: slack-notification
  source:
    url: ((slack-webhook-url))

jobs:
- name: pull-status-check
  plan:
  - get: pull-request
    version: every
    trigger: true
  - put: pull-request
    params:
      path: pull-request
      status: pending
  - task: build
    input_mapping:
      notify-src: pull-request
    file: pull-request/ci/run-tests.yml
    on_success:
      put: pull-request
      params:
        path: pull-request
        status: success
    on_failure:
      put: pull-request
      params:
        path: pull-request
        status: failure
- name: test-cg-buildpack-notify
  plan:
  - get: notify-src
    trigger: true
  - task: run-tests
    file: notify-src/ci/run-tests.yml
- name: push-cg-buildpack-notify-staging
  plan:
  - aggregate:
    - get: notify-src
      passed: [test-cg-buildpack-notify]
      trigger: true
  - put: cg-buildpack-notify-deploy-staging
    params:
      path: notify-src
      manifest: notify-src/manifest.yml
  on_failure:
    put: slack
    params:
      text: |
        :x: FAILED to deploy buildpack-notifier on ((cf-api-staging))
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: Successfully deployed buildpack-notifier on ((cf-api-staging))
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))
- name: push-cg-buildpack-notify-production
  plan:
  - aggregate:
    - get: notify-src
      passed: [push-cg-buildpack-notify-staging]
      trigger: true
  - put: cg-buildpack-notify-deploy-production
    params:
      path: notify-src
      manifest: notify-src/manifest.yml
  on_failure:
    put: slack
    params:
      text: |
        :x: FAILED to deploy buildpack-notifier on ((cf-api-production))
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: Successfully deployed buildpack-notifier on ((cf-api-production))
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))
- name: notify-customers-staging
  plan:
  - get: check-buildpack-updates
    trigger: true
  - get: notify-src
  - task: do-notify
    file: notify-src/ci/notify.yml
    params:
      CF_API: ((cf-api-staging))
      CF_ORGANIZATION: ((cf-org-staging))
      CF_SPACE: ((cf-space-staging))
      CF_USERNAME: ((deployer-username-staging))
      CF_PASSWORD: ((deployer-password-staging))
      ADDITIONAL_ARGS: ((additional-args-staging))
  on_failure:
    put: slack
    params:
      text: |
        :x: FAILED to notify customers with buildpack-notifier on ((cf-api-staging))
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))

- name: notify-customers-production
  plan:
  - get: check-buildpack-updates
    trigger: true
  - get: notify-src
  - task: do-notify
    file: notify-src/ci/notify.yml
    params:
      CF_API: ((cf-api-production))
      CF_ORGANIZATION: ((cf-org-production))
      CF_SPACE: ((cf-space-production))
      CF_USERNAME: ((deployer-username-production))
      CF_PASSWORD: ((deployer-password-production))
      ADDITIONAL_ARGS: ((additional-args-production))
  on_failure:
    put: slack
    params:
      text: |
        :x: FAILED to notify customers with buildpack-notifier on ((cf-api-production))
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))
