groups:
- name: customer-pipeline
  jobs:
  - notify-customers-prod
  - test-cg-buildpack-notify
  - push-cg-buildpack-notify-production

resource_types:
- name: semver-iam
  type: docker-image
  source:
    repository: governmentpaas/semver-resource

resources:
- name: check-buildpack-updates
  type: time
  source: {interval: 60m}
- name: notify-src
  type: git
  source:
    uri: ((cg-buildpack-notify))
    branch: ((cg-buildpack-notify-branch))
- name: cg-buildpack-notify-deploy-production
  type: cf
  source:
    api: ((cf-api-prod))
    username: ((deployer-username-prod))
    password: ((deployer-password-prod))
    organization: ((cf-org-prod))
    space: ((cf-space-prod))

jobs:
- name: test-cg-buildpack-notify
  plan:
  - get: notify-src
    trigger: true
  - task: run-tests
    file: notify-src/ci/run-tests.yml
- name: push-cg-buildpack-notify-production
  plan:
  - aggregate:
    - get: notify-src
      passed: [test-cg-buildpack-notify]
      trigger: true
  - put: cg-buildpack-notify-deploy-production
    params:
      path: notify-src
      manifest: notify-src/manifest.yml
- name: notify-customers-prod
  plan:
  - get: check-buildpack-updates
    trigger: true
  - get: notify-src
  - task: do-notify
    file: notify-src/ci/notify.yml
    params:
      SMTP_FROM: ((smtp-from))
      SMTP_PORT: ((smtp-port))
      SMTP_PASS: ((smtp-pass))
      SMTP_USER: ((smtp-user))
      SMTP_HOST: ((smtp-host))
      CF_API: ((cf-api-prod))
      CF_ORGANIZATION: ((cf-org-prod))
      CF_SPACE: ((cf-space-prod))
      CF_USERNAME: ((deployer-username-prod))
      CF_PASSWORD: ((deployer-password-prod))
      CLIENT_ID: ((client-id-prod))
      CLIENT_SECRET: ((client-secret-prod))
      ADDITIONAL_ARGS: ((additional-args))
