resource_types:
- name: semver-iam
  type: docker-image
  source:
    repository: governmentpaas/semver-resource
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:
- name: check-buildpack-updates
  type: time
  source: {interval: 60m}
- name: notify-src
  type: git
  source:
    uri: ((cg-buildpack-notify))
    branch: ((cg-buildpack-notify-branch))
- name: pull-request
  type: pull-request
  source:
    repo: ((cg-buildpack-notify-github-repo-name))
    access_token: ((status-access-token))
    every: true
- name: slack
  type: slack-notification
  source:
    url: ((slack-webhook-url))

jobs:
- name: pull-status-check
  plan:
  - get: pull-request
    version: every
    trigger: true
  - put: pull-request
    params:
      path: pull-request
      status: pending
  - task: build
    input_mapping:
      notify-src: pull-request
    file: pull-request/ci/run-tests.yml
    on_success:
      put: pull-request
      params:
        path: pull-request
        status: success
    on_failure:
      put: pull-request
      params:
        path: pull-request
        status: failure
- name: test-cg-buildpack-notify
  plan:
  - get: notify-src
    trigger: true
  - task: run-tests
    file: notify-src/ci/run-tests.yml
- name: notify-customers-staging
  plan:
  - get: check-buildpack-updates
    trigger: true
  - get: notify-src
  - task: do-notify
    file: notify-src/ci/notify.yml
    params:
      CF_API: ((cf-api-staging))
      CLIENT_ID: ((cf-client-id-staging))
      CLIENT_SECRET: ((cf-client-secret-staging))
      SMTP_FROM: ((smtp-from-staging))
      SMTP_USER: ((smtp-from-staging))
      SMTP_PASSWORD: ((smtp-from-staging))
      SMTP_HOST: ((smtp-from-staging))
      SMTP_PORT: ((smtp-from-staging))
  on_failure:
    put: slack
    params:
      text: |
        :x: FAILED to notify customers with buildpack-notifier on ((cf-api-staging))
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))

- name: notify-customers-production
  plan:
  - get: check-buildpack-updates
    trigger: true
  - get: notify-src
  - task: do-notify
    file: notify-src/ci/notify.yml
    params:
      CF_API: ((cf-api-production))
      CLIENT_ID: ((cf-client-id-production))
      CLIENT_SECRET: ((cf-client-secret-production))
      SMTP_FROM: ((smtp-from-production))
      SMTP_USER: ((smtp-from-production))
      SMTP_PASSWORD: ((smtp-from-production))
      SMTP_HOST: ((smtp-from-production))
      SMTP_PORT: ((smtp-from-production))
  on_failure:
    put: slack
    params:
      text: |
        :x: FAILED to notify customers with buildpack-notifier on ((cf-api-production))
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))
